### ISSUE TITLE
您的moss sft采样策略

### ISSUE THREAD

**Issue by nuoma** [zejunwang1/LLMTuner#4]
您好，看到了moss-003有30w和21w两个版本，想问一下采样策略是什么样子的？
我目前只是根据6个类别进行了随机采样1万条做测试，但并没有想明白什么样的采样策略？是做个传统的聚类还是根据原始问题用BM25去计算相似度。
不是是否可以分享一下思路，谢谢！

**Comment by zejunwang1** [comment]
30w 和 21w 这两份数据也是我随机采样的，之前训练的时候觉得 moss 的 107w 数据量太大了，就随机采样了两份
